[build]
publish = "."
command = "echo 'No build command needed'"

[functions]
directory = "netlify/functions"

[secrets_scanning]
enabled = false # or set to true if you want to use the ignore lists below
omit_paths = [
  "about.html",
  "analytics.js"
]