name: Auto Post Instagram

on:
  schedule:
    - cron: "0 12 * * *"   # every day at 12:00 UTC
  workflow_dispatch:

jobs:
  post-confessions:
    runs-on: ubuntu-latest

    env:
      IG_USERNAME: ${{ secrets.IG_USERNAME }}
      IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
      FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install instagrapi Pillow firebase-admin google-cloud-firestore

      - name: Run bot
        run: python bot.py
