name: Auto Post Instagram

on:
  schedule:
    - cron: '0 12 * * *'  # daily at 12:00 UTC
  workflow_dispatch:

jobs:
  post-confessions:
    runs-on: ubuntu-latest
    env:
      IG_USERNAME: ${{ secrets.IG_USERNAME }}
      IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
      FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install instagrapi pyotp firebase-admin Pillow

      - name: Run Instagram Bot
        run: python3 auto-Instagram-posting-bot/bot.py
