name: Auto Post Confessions

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour
  workflow_dispatch:  # manual trigger

jobs:
  post-confessions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Install dependencies
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r auto-Instagram-posting-bot/requirements.txt
          python3 -m pip install instagrapi pyotp Pillow

      # Run bot
      - name: Run bot
        run: python3 auto-Instagram-posting-bot/bot.py
        env:
          FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}
